# Generated by @agentflow/sdk OpenAPI generator. Do not edit manually.
from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional, Union
import json
import urllib.request
import urllib.error
import urllib.parse
from .models import *

class AgentFlowApiError(Exception):
    def __init__(self, message: str, status_code: int = 500, error_code: str = "API_ERROR", details: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.message = message
        self.status_code = status_code
        self.error_code = error_code
        self.details = details or {}

class AgentFlowClient:
    """AgentFlow Official Python Client generated from OpenAPI 3.1."""

    def __init__(
        self,
        base_url: str = "http://localhost:3001",
        token: Optional[str] = None,
        api_key: Optional[str] = None,
        org_id: Optional[str] = None,
        timeout: float = 30.0,
        headers: Optional[Dict[str, str]] = None,
    ):
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.api_key = api_key
        self.org_id = org_id
        self.timeout = timeout
        self.headers = headers or {}

    def set_token(self, token: Optional[str]) -> None:
        self.token = token

    def set_api_key(self, api_key: Optional[str]) -> None:
        self.api_key = api_key

    def set_org_id(self, org_id: Optional[str]) -> None:
        self.org_id = org_id

    def _request(
        self,
        method: str,
        path: str,
        params: Optional[Dict[str, Any]] = None,
        json: Optional[Any] = None,
        requires_auth: bool = True,
    ) -> Any:
        url = f"{self.base_url}/{path.lstrip('/')}"
        if params:
            query = urllib.parse.urlencode({k: str(v) for k, v in params.items() if v is not None})
            if query:
                url = f"{url}?{query}"

        req_headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            **self.headers,
        }

        if requires_auth:
            if self.token:
                req_headers["Authorization"] = self.token if self.token.startswith("Bearer ") else f"Bearer {self.token}"
            elif self.api_key:
                req_headers["x-api-key"] = self.api_key
            if self.org_id:
                req_headers["x-org-id"] = self.org_id

        data = None
        if json is not None:
            data = urllib.request.json.dumps(json).encode("utf-8") if hasattr(urllib.request, "json") else __import__("json").dumps(json).encode("utf-8")

        req = urllib.request.Request(url=url, data=data, headers=req_headers, method=method)

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                status = resp.getcode()
                if status == 204:
                    return None
                raw = resp.read().decode("utf-8")
                content_type = resp.headers.get("content-type", "")
                if "application/json" in content_type:
                    res_data = __import__("json").loads(raw)
                    if isinstance(res_data, dict) and res_data.get("jsonrpc") == "2.0" and "result" in res_data:
                        return res_data["result"]
                    return res_data
                return raw
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8")
            try:
                payload = __import__("json").loads(err_body)
                msg = payload.get("error") or payload.get("message") or str(e)
                code = payload.get("code") or "HTTP_ERROR"
                details = payload.get("details")
                raise AgentFlowApiError(msg, status_code=e.code, error_code=code, details=details)
            except (ValueError, KeyError):
                raise AgentFlowApiError(err_body or str(e), status_code=e.code, error_code="HTTP_ERROR")
        except Exception as e:
            if isinstance(e, AgentFlowApiError):
                raise
            raise AgentFlowApiError(str(e), status_code=500, error_code="NETWORK_ERROR")

    def health(self) -> Dict[str, Any]:
        return self._request(method="GET", path="/health", requires_auth=False)

    def delete_api_api_keys_by_id(self, id_: str) -> OkResponse:
        """Revoke a personal API key"""
        return self._request(
            method="DELETE",
            path=f"/api/api-keys/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def delete_api_credentials_by_id(self, id_: str) -> OkResponse:
        """Delete a credential"""
        return self._request(
            method="DELETE",
            path=f"/api/credentials/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def delete_api_webhooks_by_id(self, id_: str) -> OkResponse:
        """Delete a webhook"""
        return self._request(
            method="DELETE",
            path=f"/api/webhooks/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def delete_api_workflows_by_id(self, id_: str) -> OkResponse:
        """Delete a workflow (and its canvas)"""
        return self._request(
            method="DELETE",
            path=f"/api/workflows/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_api_keys(self) -> List[ApiKey]:
        """List personal API keys (without values)"""
        return self._request(
            method="GET",
            path=f"/api/api-keys",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_approvals(self, page: int, limit: int) -> List[Approval]:
        """List pending approvals across your organizations"""
        return self._request(
            method="GET",
            path=f"/api/approvals",
            params={k: v for k, v in {"page": page, "limit": limit}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_auth_by_provider(self, provider: Literal["google", "microsoft", "apple"]) -> Any:
        """Start a social login flow"""
        return self._request(
            method="GET",
            path=f"/api/auth/{provider}",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_api_auth_by_provider_callback(self, provider: Literal["google", "microsoft", "apple"], code: Optional[str] = None, state: Optional[str] = None, error: Optional[str] = None) -> Any:
        """OAuth callback (browser-facing)"""
        return self._request(
            method="GET",
            path=f"/api/auth/{provider}/callback",
            params={k: v for k, v in {"code": code, "state": state, "error": error}.items() if v is not None},
            json=None,
            requires_auth=False,
        )

    def get_api_billing_subscription(self) -> Subscription:
        """Current subscription (or free)"""
        return self._request(
            method="GET",
            path=f"/api/billing/subscription",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_billing_usage(self, page: int, limit: int) -> List[UsageRecord]:
        """Usage records for the current user"""
        return self._request(
            method="GET",
            path=f"/api/billing/usage",
            params={k: v for k, v in {"page": page, "limit": limit}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_credentials(self, page: int, limit: int) -> List[Credential]:
        """List credentials (masked)"""
        return self._request(
            method="GET",
            path=f"/api/credentials",
            params={k: v for k, v in {"page": page, "limit": limit}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_credentials_by_id_reveal(self, id_: str) -> CredentialReveal:
        """Reveal a credential's decrypted value"""
        return self._request(
            method="GET",
            path=f"/api/credentials/{id_}/reveal",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_docs(self) -> Any:
        """OpenAPI 3.1 JSON document"""
        return self._request(
            method="GET",
            path=f"/api/docs",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_api_executions(self, page: int, limit: int, workflow_id: Optional[str] = None, status: Optional[Literal["PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", "WAITING_APPROVAL"]] = None) -> List[Union[Execution, Dict[str, Any]]]:
        """List executions"""
        return self._request(
            method="GET",
            path=f"/api/executions",
            params={k: v for k, v in {"page": page, "limit": limit, "workflowId": workflow_id, "status": status}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_executions_by_id(self, id_: str) -> Union[Execution, Dict[str, Any]]:
        """Get execution details (nodes, approvals, workflow)"""
        return self._request(
            method="GET",
            path=f"/api/executions/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_executions_by_id_nodes(self, id_: str) -> List[NodeExecution]:
        """List node-level logs of an execution"""
        return self._request(
            method="GET",
            path=f"/api/executions/{id_}/nodes",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_mcp_sse(self) -> Any:
        """Open MCP streaming SSE connection"""
        return self._request(
            method="GET",
            path=f"/api/mcp/sse",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_orgs(self) -> List[OrgSummary]:
        """List organizations the user belongs to"""
        return self._request(
            method="GET",
            path=f"/api/orgs",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_orgs_by_id(self, id_: str) -> OrgSummary:
        """Get an organization"""
        return self._request(
            method="GET",
            path=f"/api/orgs/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_orgs_by_id_members(self, id_: str) -> List[Dict[str, Any]]:
        """List members of an organization"""
        return self._request(
            method="GET",
            path=f"/api/orgs/{id_}/members",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_orgs_by_id_usage(self, id_: str) -> Dict[str, Any]:
        """Get organization usage statistics and quota limits"""
        return self._request(
            method="GET",
            path=f"/api/orgs/{id_}/usage",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_settings(self) -> Settings:
        """Current user profile and organizations"""
        return self._request(
            method="GET",
            path=f"/api/settings",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_api_telemetry_stats(self) -> Dict[str, Any]:
        """Telemetry summary metrics in JSON format"""
        return self._request(
            method="GET",
            path=f"/api/telemetry/stats",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_api_webhooks(self, page: int, limit: int) -> List[Webhook]:
        """List webhooks of your organizations"""
        return self._request(
            method="GET",
            path=f"/api/webhooks",
            params={k: v for k, v in {"page": page, "limit": limit}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_workflows(self, page: int, limit: int) -> List[Workflow]:
        """List workflows of the active organization"""
        return self._request(
            method="GET",
            path=f"/api/workflows",
            params={k: v for k, v in {"page": page, "limit": limit}.items() if v is not None},
            json=None,
            requires_auth=True,
        )

    def get_api_workflows_by_id(self, id_: str) -> Workflow:
        """Get a workflow with canvas and latest version"""
        return self._request(
            method="GET",
            path=f"/api/workflows/{id_}",
            params=None,
            json=None,
            requires_auth=True,
        )

    def get_docs(self) -> Any:
        """Interactive Swagger UI documentation"""
        return self._request(
            method="GET",
            path=f"/docs",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_docs_json(self) -> Any:
        """OpenAPI 3.1 JSON document alias"""
        return self._request(
            method="GET",
            path=f"/docs/json",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_health(self) -> Dict[str, Any]:
        """Advanced system health check"""
        return self._request(
            method="GET",
            path=f"/health",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_mcp_status(self) -> Dict[str, Any]:
        """Get MCP server health and exposed tool metrics"""
        return self._request(
            method="GET",
            path=f"/mcp/status",
            params=None,
            json=None,
            requires_auth=False,
        )

    def get_metrics(self) -> Any:
        """Prometheus formatted OpenTelemetry metrics"""
        return self._request(
            method="GET",
            path=f"/metrics",
            params=None,
            json=None,
            requires_auth=False,
        )

    def patch_api_workflows_by_id(self, id_: str, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Workflow:
        """Partially update workflow metadata and/or canvas"""
        return self._request(
            method="PATCH",
            path=f"/api/workflows/{id_}",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_ai_generate(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Dict[str, Any]:
        """Generate a workflow from a natural-language prompt"""
        return self._request(
            method="POST",
            path=f"/api/ai/generate",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_api_keys(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> ApiKeyCreated:
        """Create a personal API key"""
        return self._request(
            method="POST",
            path=f"/api/api-keys",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_approvals_by_id_approve(self, id_: str) -> OkResponse:
        """Approve a pending approval"""
        return self._request(
            method="POST",
            path=f"/api/approvals/{id_}/approve",
            params=None,
            json=None,
            requires_auth=True,
        )

    def post_api_approvals_by_id_reject(self, id_: str) -> OkResponse:
        """Reject a pending approval"""
        return self._request(
            method="POST",
            path=f"/api/approvals/{id_}/reject",
            params=None,
            json=None,
            requires_auth=True,
        )

    def post_api_auth_forgot_password(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> MessageResponse:
        """Request a password reset email"""
        return self._request(
            method="POST",
            path=f"/api/auth/forgot-password",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=False,
        )

    def post_api_auth_login(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> LoginResponse:
        """Exchange email + password for tokens"""
        return self._request(
            method="POST",
            path=f"/api/auth/login",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=False,
        )

    def post_api_auth_logout(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Any:
        """Revoke a refresh token"""
        return self._request(
            method="POST",
            path=f"/api/auth/logout",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=False,
        )

    def post_api_auth_refresh(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> TokenPair:
        """Rotate a refresh token"""
        return self._request(
            method="POST",
            path=f"/api/auth/refresh",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=False,
        )

    def post_api_auth_register(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> MessageResponse:
        """Create an account (with a default organization)"""
        return self._request(
            method="POST",
            path=f"/api/auth/register",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=False,
        )

    def post_api_billing_checkout(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> CheckoutResponse:
        """Create a Stripe Checkout session"""
        return self._request(
            method="POST",
            path=f"/api/billing/checkout",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_billing_webhook(self) -> Dict[str, Any]:
        """Stripe webhook receiver"""
        return self._request(
            method="POST",
            path=f"/api/billing/webhook",
            params=None,
            json=None,
            requires_auth=True,
        )

    def post_api_credentials(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Credential:
        """Store an encrypted credential"""
        return self._request(
            method="POST",
            path=f"/api/credentials",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_executions_by_id_cancel(self, id_: str) -> OkResponse:
        """Cancel a pending or running execution"""
        return self._request(
            method="POST",
            path=f"/api/executions/{id_}/cancel",
            params=None,
            json=None,
            requires_auth=True,
        )

    def post_api_executions_trigger(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Execution:
        """Trigger a workflow execution via API"""
        return self._request(
            method="POST",
            path=f"/api/executions/trigger",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_mcp(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Dict[str, Any]:
        """MCP JSON-RPC 2.0 message handler"""
        return self._request(
            method="POST",
            path=f"/api/mcp",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_orgs(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> OrgSummary:
        """Create an organization"""
        return self._request(
            method="POST",
            path=f"/api/orgs",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_orgs_by_id_invite(self, id_: str, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Dict[str, Any]:
        """Add a registered user to the organization"""
        return self._request(
            method="POST",
            path=f"/api/orgs/{id_}/invite",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_webhooks(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> WebhookCreated:
        """Create a webhook trigger"""
        return self._request(
            method="POST",
            path=f"/api/webhooks",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_webhooks_trigger_by_path(self, path: str, body: Optional[Union[Any, Dict[str, Any]]] = None) -> TriggerAccepted:
        """Invoke a webhook (public, signed)"""
        return self._request(
            method="POST",
            path=f"/api/webhooks/trigger/{path}",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_workflows(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Workflow:
        """Create a workflow"""
        return self._request(
            method="POST",
            path=f"/api/workflows",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def post_api_workflows_by_id_run(self, id_: str) -> Execution:
        """Run a workflow manually"""
        return self._request(
            method="POST",
            path=f"/api/workflows/{id_}/run",
            params=None,
            json=None,
            requires_auth=True,
        )

    def post_mcp_token(self) -> Dict[str, Any]:
        """Generate an MCP API token"""
        return self._request(
            method="POST",
            path=f"/mcp/token",
            params=None,
            json=None,
            requires_auth=False,
        )

    def put_api_orgs_by_id(self, id_: str, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> OrgSummary:
        """Rename an organization (OWNER/ADMIN only)"""
        return self._request(
            method="PUT",
            path=f"/api/orgs/{id_}",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def put_api_settings(self, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> OkResponse:
        """Update the user profile"""
        return self._request(
            method="PUT",
            path=f"/api/settings",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def put_api_workflows_by_id(self, id_: str, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Workflow:
        """Update workflow metadata and/or canvas"""
        return self._request(
            method="PUT",
            path=f"/api/workflows/{id_}",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

    def put_api_workflows_by_id_canvas(self, id_: str, body: Optional[Union[Dict[str, Any], Dict[str, Any]]] = None) -> Dict[str, Any]:
        """Replace the workflow canvas"""
        return self._request(
            method="PUT",
            path=f"/api/workflows/{id_}/canvas",
            params=None,
            json=body if isinstance(body, dict) else (body.model_dump(by_alias=True) if hasattr(body, 'model_dump') else body),
            requires_auth=True,
        )

