# Generated by @agentflow/sdk OpenAPI generator. Do not edit manually.
from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field

class ApiError(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    error: str = Field(...)
    code: str = Field(...)
    details: Optional[Dict[str, Any]] = Field(default=None)

class ApiKey(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    last_used: Optional[str] = Field(default=None, alias="lastUsed")
    expires_at: Optional[str] = Field(default=None, alias="expiresAt")
    created_at: str = Field(..., alias="createdAt")

class ApiKeyCreated(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    key: str = Field(...)
    created_at: str = Field(..., alias="createdAt")

class Approval(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    execution_id: str = Field(..., alias="executionId")
    status: Literal["PENDING", "APPROVED", "REJECTED"] = Field(...)
    created_at: str = Field(..., alias="createdAt")
    decided_at: Optional[str] = Field(default=None, alias="decidedAt")
    execution: Optional[Dict[str, Any]] = Field(default=None)

class CheckoutResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    url: str = Field(...)
    session_id: str = Field(..., alias="sessionId")

class Credential(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    type_: Literal["api_key", "oauth2", "basic", "token"] = Field(..., alias="type")
    provider: str = Field(...)
    created_at: str = Field(..., alias="createdAt")
    data: Dict[str, Any] = Field(...)

class CredentialReveal(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    type_: Literal["api_key", "oauth2", "basic", "token"] = Field(..., alias="type")
    provider: str = Field(...)
    data: Dict[str, Any] = Field(...)

class Execution(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    workflow_id: str = Field(..., alias="workflowId")
    org_id: Optional[str] = Field(default=None, alias="orgId")
    status: Literal["PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", "WAITING_APPROVAL"] = Field(...)
    trigger: Literal["manual", "webhook", "cron", "api"] = Field(...)
    input_: Optional[Dict[str, Any]] = Field(default=None, alias="input")
    output: Optional[Dict[str, Any]] = Field(default=None)
    error: Optional[str] = Field(default=None)
    started_at: str = Field(..., alias="startedAt")
    finished_at: Optional[str] = Field(default=None, alias="finishedAt")

class LoginResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    token: str = Field(...)
    refresh_token: str = Field(..., alias="refreshToken")
    user: Dict[str, Any] = Field(...)
    org: Optional[Dict[str, Any]] = Field(default=None)

class MessageResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    message: str = Field(...)

class NodeExecution(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    execution_id: str = Field(..., alias="executionId")
    status: Literal["PENDING", "RUNNING", "SUCCESS", "FAILED", "SKIPPED"] = Field(...)
    input_: Optional[Dict[str, Any]] = Field(default=None, alias="input")
    output: Optional[Dict[str, Any]] = Field(default=None)
    error: Optional[str] = Field(default=None)
    started_at: str = Field(..., alias="startedAt")
    finished_at: Optional[str] = Field(default=None, alias="finishedAt")

class OkResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    ok: Literal[true] = Field(...)

class OrgSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    slug: str = Field(...)
    role: Literal["OWNER", "ADMIN", "MEMBER", "VIEWER"] = Field(...)
    plan: Optional[Literal["FREE", "STARTER", "PRO", "ENTERPRISE"]] = Field(default=None)

class Settings(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    email: str = Field(...)
    name: str = Field(...)
    avatar_url: Optional[str] = Field(default=None, alias="avatarUrl")
    email_verified: bool = Field(..., alias="emailVerified")
    created_at: str = Field(..., alias="createdAt")
    organizations: List[Dict[str, Any]] = Field(...)

Subscription = Union[Dict[str, Any], Dict[str, Any]]

class TokenPair(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    token: str = Field(...)
    refresh_token: str = Field(..., alias="refreshToken")

class TriggerAccepted(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    execution_id: str = Field(..., alias="executionId")

class UsageRecord(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    type_: Literal["execution"] = Field(..., alias="type")
    quantity: int = Field(...)
    created_at: str = Field(..., alias="createdAt")

class User(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    email: str = Field(...)
    name: str = Field(...)

class Webhook(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    path: str = Field(...)
    method: Literal["GET", "POST", "PUT", "DELETE"] = Field(...)
    workflow_id: Optional[str] = Field(default=None, alias="workflowId")
    active: bool = Field(...)
    created_at: str = Field(..., alias="createdAt")
    workflow: Optional[Dict[str, Any]] = Field(default=None)

class WebhookCreated(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    path: str = Field(...)
    method: Literal["GET", "POST", "PUT", "DELETE"] = Field(...)
    workflow_id: Optional[str] = Field(default=None, alias="workflowId")
    active: bool = Field(...)
    created_at: str = Field(..., alias="createdAt")
    workflow: Optional[Dict[str, Any]] = Field(default=None)
    secret: str = Field(...)

class Workflow(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")
    id_: str = Field(..., alias="id")
    name: str = Field(...)
    description: Optional[str] = Field(default=None)
    status: Literal["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"] = Field(...)
    org_id: str = Field(..., alias="orgId")
    created_at: str = Field(..., alias="createdAt")
    updated_at: str = Field(..., alias="updatedAt")
    nodes: Optional[List[Dict[str, Any]]] = Field(default=None)
    edges: Optional[List[Dict[str, Any]]] = Field(default=None)

