-- Reversal for 000000000000_baseline
DROP TABLE IF EXISTS "ApiKey" CASCADE;
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "Subscription" CASCADE;
DROP TABLE IF EXISTS "UsageRecord" CASCADE;
DROP TABLE IF EXISTS "Approval" CASCADE;
DROP TABLE IF EXISTS "Webhook" CASCADE;
DROP TABLE IF EXISTS "Integration" CASCADE;
DROP TABLE IF EXISTS "Credential" CASCADE;
DROP TABLE IF EXISTS "NodeExecution" CASCADE;
DROP TABLE IF EXISTS "WorkflowExecution" CASCADE;
DROP TABLE IF EXISTS "WorkflowEdge" CASCADE;
DROP TABLE IF EXISTS "WorkflowNode" CASCADE;
DROP TABLE IF EXISTS "WorkflowVersion" CASCADE;
DROP TABLE IF EXISTS "Workflow" CASCADE;
DROP TABLE IF EXISTS "OrganizationMember" CASCADE;
DROP TABLE IF EXISTS "Organization" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "RefreshToken" CASCADE;

DROP TYPE IF EXISTS "ApprovalStatus";
DROP TYPE IF EXISTS "ExecutionStatus";
DROP TYPE IF EXISTS "WorkflowStatus";
DROP TYPE IF EXISTS "MemberRole";
DROP TYPE IF EXISTS "Plan";
