"use client";

import { useState } from "react";
import { CreditCard, Gauge, Mail, Save, Settings2, UsersRound } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Progress } from "@/components/ui/Progress";
import { Select } from "@/components/ui/Select";
import { TabItem, Tabs } from "@/components/ui/Tabs";

const tabs: TabItem[] = [
  { id: "general", label: "General", icon: <Settings2 className="h-3.5 w-3.5" /> },
  { id: "team", label: "Team", icon: <UsersRound className="h-3.5 w-3.5" /> },
  { id: "billing", label: "Billing", icon: <CreditCard className="h-3.5 w-3.5" /> },
  { id: "usage", label: "Usage", icon: <Gauge className="h-3.5 w-3.5" /> },
];

export default function SettingsPage() {
  const [tab, setTab] = useState("general");
  const [message, setMessage] = useState("");
  function save() { setMessage("Settings saved"); window.setTimeout(() => setMessage(""), 2200); }
  return <AppLayout><div className="animate-in fade-in duration-300"><div><h1 className="text-2xl font-semibold text-zinc-50">Settings</h1><p className="mt-1 text-sm text-zinc-500">Manage your workspace and account preferences</p></div><div className="mt-8"><Tabs items={tabs} value={tab} onChange={setTab} /></div><div className="mt-8 max-w-3xl">{tab === "general" ? <GeneralSettings onSave={save} /> : tab === "team" ? <TeamSettings onSave={save} /> : tab === "billing" ? <BillingSettings /> : <UsageSettings />}</div>{message ? <div className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-lg border border-green-500/20 bg-zinc-900 px-4 py-2.5 text-xs text-green-300 shadow-2xl shadow-black/40"><Save className="h-3.5 w-3.5" />{message}</div> : null}</div></AppLayout>;
}

function GeneralSettings({ onSave }: { onSave: () => void }) {
  return <Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div><h2 className="text-lg font-medium text-zinc-100">Workspace profile</h2><p className="mt-1 text-sm text-zinc-500">The identity your team sees across AgentFlow.</p></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Input label="Workspace name" defaultValue="Northstar Labs" /><Input label="Workspace slug" defaultValue="northstar-labs" /><Select label="Default timezone" defaultValue="America/Sao_Paulo" options={[{ value: "America/Sao_Paulo", label: "São Paulo (GMT-3)" }, { value: "America/New_York", label: "New York (GMT-4)" }, { value: "Europe/London", label: "London (GMT+1)" }, { value: "UTC", label: "UTC" }]} /><Select label="Default execution mode" defaultValue="safe" options={[{ value: "safe", label: "Safe — confirm external writes" }, { value: "live", label: "Live — run immediately" }]} /></div><div className="mt-6 border-t border-white/10 pt-6"><h3 className="text-sm font-medium text-zinc-200">Notifications</h3><div className="mt-4 space-y-4"><ToggleRow title="Execution failures" description="Email workspace admins when a workflow fails." defaultChecked /><ToggleRow title="Approval requests" description="Send a digest when human decisions are waiting." defaultChecked /><ToggleRow title="Weekly summary" description="Receive a Monday summary of workspace activity." /></div></div><div className="mt-6 flex justify-end"><Button onClick={onSave} className="bg-n8n-accent hover:bg-n8n-accent-dark text-white rounded-md px-4 py-2 text-sm font-medium"><Save className="h-3.5 w-3.5" /> Save changes</Button></div></Card>;
}

function TeamSettings({ onSave }: { onSave: () => void }) {
  return <div className="space-y-6"><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-medium text-zinc-100">Team members</h2><p className="mt-1 text-sm text-zinc-500">8 of 15 seats are assigned.</p></div><Button size="sm" className="bg-n8n-accent hover:bg-n8n-accent-dark text-white rounded-md px-4 py-2 text-sm font-medium">Invite member</Button></div><div className="mt-6 divide-y divide-white/10">{[{ name: "Victor Silva", email: "victor@northstar.dev", role: "Owner", initials: "VS" }, { name: "Maya Chen", email: "maya@northstar.dev", role: "Admin", initials: "MC" }, { name: "Jules Martin", email: "jules@northstar.dev", role: "Member", initials: "JM" }, { name: "Priya Shah", email: "priya@northstar.dev", role: "Viewer", initials: "PS" }].map((member) => <div key={member.email} className="flex items-center justify-between gap-3 py-4"><div className="flex min-w-0 items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/10 text-[10px] font-semibold text-zinc-300">{member.initials}</span><div className="min-w-0"><p className="truncate text-sm font-medium text-zinc-200">{member.name}</p><p className="truncate text-xs text-zinc-600">{member.email}</p></div></div><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-zinc-500">{member.role}</span></div>)}</div></Card><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><h2 className="text-lg font-medium text-zinc-100">Invite defaults</h2><p className="mt-1 text-sm text-zinc-500">Choose the permission new teammates receive.</p><div className="mt-5 max-w-xs"><Select label="Default role" defaultValue="MEMBER" options={[{ value: "MEMBER", label: "Member — can build and run" }, { value: "VIEWER", label: "Viewer — read only" }]} /></div><div className="mt-6 flex justify-end"><Button onClick={onSave} className="bg-n8n-accent hover:bg-n8n-accent-dark text-white rounded-md px-4 py-2 text-sm font-medium"><Save className="h-3.5 w-3.5" /> Save team settings</Button></div></Card></div>;
}

function BillingSettings() {
  return <div className="space-y-6"><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><span className="rounded-full bg-n8n-accent/15 px-2.5 py-1 text-xs font-medium text-n8n-accent">Pro plan</span><h2 className="mt-4 text-2xl font-semibold text-zinc-50">$39 <span className="text-sm font-normal text-zinc-500">/ user / month</span></h2><p className="mt-2 text-sm text-zinc-500">Your next invoice is Sep 01, 2026.</p></div><Button variant="secondary" className="bg-n8n-accent hover:bg-n8n-accent-dark text-white rounded-md px-4 py-2 text-sm font-medium">Manage subscription</Button></div><div className="mt-6 border-t border-white/10 pt-5"><Progress value={71} label="Monthly execution usage" helper="7,120 of 10,000" /></div></Card><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div className="flex items-center gap-2"><CreditCard className="h-4 w-4 text-zinc-400" /><h2 className="text-lg font-medium text-zinc-100">Payment method</h2></div><div className="mt-5 flex items-center justify-between rounded-lg border border-white/10 bg-zinc-950/60 p-4"><div className="flex items-center gap-3"><span className="rounded bg-blue-500/10 px-2 py-1 text-xs font-semibold text-blue-400">VISA</span><div><p className="text-sm text-zinc-200">•••• 4242</p><p className="text-xs text-zinc-600">Expires 08/28</p></div></div><button type="button" className="text-xs text-n8n-accent hover:text-n8n-accent-dark">Update</button></div></Card></div>;
}

function UsageSettings() {
  return <div className="space-y-6"><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-medium text-zinc-100">Usage overview</h2><p className="mt-1 text-sm text-zinc-500">A clear view of what your workspace is consuming.</p></div><Gauge className="h-5 w-5 text-n8n-accent" /></div><div className="mt-7 space-y-6"><Progress value={71} label="Executions" helper="7,120 / 10,000" /><Progress value={53} label="AI tokens" helper="5.3M / 10M" /><Progress value={34} label="Storage" helper="3.4 GB / 10 GB" /></div></Card><Card className="bg-n8n-panel border border-white/10 rounded-lg p-5"><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-zinc-400" /><h2 className="text-lg font-medium text-zinc-100">Usage alerts</h2></div><p className="mt-1 text-sm text-zinc-500">Get a heads-up before limits affect your flows.</p><div className="mt-5 max-w-xs"><Select label="Alert threshold" defaultValue="80" options={[{ value: "70", label: "70% of allowance" }, { value: "80", label: "80% of allowance" }, { value: "90", label: "90% of allowance" }]} /></div></Card></div>;
}

function ToggleRow({ title, description, defaultChecked = false }: { title: string; description: string; defaultChecked?: boolean }) {
  const [checked, setChecked] = useState(defaultChecked);
  return <div className="flex items-center justify-between gap-4"><div><p className="text-sm text-zinc-300">{title}</p><p className="mt-1 text-xs text-zinc-600">{description}</p></div><button type="button" role="switch" aria-checked={checked} onClick={() => setChecked((value) => !value)} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? "bg-n8n-accent" : "bg-zinc-700"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-transform ${checked ? "left-6" : "left-1"}`} /></button></div>;
}
