export {
  computeWorkflowDiff,
  normalizeSnapshotNodes,
  normalizeSnapshotEdges,
  deepEqual,
  type WorkflowNodeSnapshot,
  type WorkflowEdgeSnapshot,
  type WorkflowSnapshot,
  type FieldDiff,
  type NodeModificationDiff,
  type EdgeModificationDiff,
  type VisualNodeDiffMarker,
  type VisualEdgeDiffMarker,
  type WorkflowVisualDiffMap,
  type WorkflowDiffResult,
} from "@agentflow/shared";
