"use client";
import { AppLayout } from "@/components/layout/AppLayout";
import Link from "next/link";
const tiers=[
  {name:"Starter",price:"150 R$",sub:"/mo, billed monthly",desc:"Perfect for getting started quickly and seeing the power of AgentFlow",cta:"Select plan",primary:"bg-emerald-600 hover:bg-emerald-500",features:["2.5k workflow executions (unlimited steps)","∞ unlimited active workflows","Workflows run 24/7","1 shared project","5 concurrent executions","Unlimited users","2,300 AI credits/mo","Community support","1 day execution history"]},
  {name:"Pro",price:"375 R$",sub:"/mo, billed monthly",desc:"Optimal for a team collaborating to run more workflows",cta:"Select plan",primary:"bg-emerald-600 hover:bg-emerald-500",features:["10k workflow executions","∞ unlimited active workflows","Everything in Starter, plus:","3 shared projects","20 concurrent executions","7 days of insights","5,700 AI credits/mo","Admin roles","Global variables","5 day workflow history","Execution search"]},
  {name:"Enterprise",price:"Custom",sub:"",desc:"Ideal for businesses with strict security and performance requirements",cta:"Contact us",primary:"border border-violet-500/40 text-violet-300 hover:bg-violet-500/10 bg-transparent",features:["∞ unlimited workflow executions","∞ unlimited active workflows","Everything in Pro, plus:","Unlimited shared projects","200+ concurrent executions","365 days of insights","SSO SAML & LDAP","Different environments","External secret store","Log streaming","Git version control","Custom SLA support"]},
];
export default function PlansPage(){ return <AppLayout><div className=""><Link href="/billing" className="text-xs text-zinc-400 hover:text-zinc-200">← Go back</Link><div className="mt-2 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><h1 className="text-3xl font-semibold text-zinc-50">Choose your plan</h1><div className="flex items-center rounded-lg border border-white/10 bg-zinc-900 p-0.5"><span className="bg-zinc-800 text-white rounded px-3 py-1 text-xs font-medium">Monthly</span><span className="text-zinc-400 px-3 py-1 text-xs">Annually (Save 17%)</span></div></div><div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">{tiers.map(t=><div key={t.name} className="rounded-xl border border-white/10 bg-zinc-900 p-6 flex flex-col"><p className="text-xs text-zinc-500">{t.desc}</p><p className="mt-4 text-2xl font-semibold text-zinc-50">{t.price} <span className="text-xs font-normal text-zinc-500">{t.sub}</span></p><button className={`mt-4 rounded-md px-4 py-2 text-sm font-medium text-white ${t.primary}`}>{t.cta}</button><ul className="mt-6 space-y-1.5 text-xs text-zinc-400">{t.features.map(f=><li key={f} className="flex gap-2"><span className="text-emerald-500">✓</span>{f}</li>)}</ul></div>)}</div></div></AppLayout>; }
