import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { computeWorkflowDiff, type WorkflowSnapshot } from "@agentflow/shared";
import { getNodeMeta, createNodeData, createCanvasNode, type WorkflowNodeData } from "../src/lib/workflow";

describe("Workflow Visual Diff & React Flow Integration", () => {
  it("computes visual diff markers for added, removed, and modified nodes", () => {
    const v1: WorkflowSnapshot = {
      nodes: [
        { id: "node-1", type: "webhook", label: "Initial Trigger", config: { path: "/test" } },
        { id: "node-2", type: "http", label: "Call API", config: { url: "https://v1.api.com" } },
      ],
      edges: [
        { id: "e-1-2", source: "node-1", target: "node-2" },
      ],
    };

    const v2: WorkflowSnapshot = {
      nodes: [
        { id: "node-1", type: "webhook", label: "Initial Trigger (Updated)", config: { path: "/test" } },
        { id: "node-3", type: "discord", label: "Alert Discord", config: { channel: "#ops" } },
      ],
      edges: [
        { id: "e-1-3", source: "node-1", target: "node-3" },
      ],
    };

    const diff = computeWorkflowDiff(v1, v2);

    assert.equal(diff.summary.totalChanges, 5); // 1 node modified, 1 node removed, 1 node added, 1 edge removed, 1 edge added
    assert.equal(diff.nodesAdded.length, 1);
    assert.equal(diff.nodesRemoved.length, 1);
    assert.equal(diff.nodesModified.length, 1);

    // Verify visualMap generated by @agentflow/shared
    assert.ok(diff.visualMap);
    assert.ok(diff.visualMap.nodes["node-3"]);
    assert.equal(diff.visualMap.nodes["node-3"].status, "added");
    assert.equal(diff.visualMap.nodes["node-3"].badgeLabel, "+ ADDED");
    assert.match(diff.visualMap.nodes["node-3"].styleClass, /ring-emerald-500/);

    assert.ok(diff.visualMap.nodes["node-2"]);
    assert.equal(diff.visualMap.nodes["node-2"].status, "removed");
    assert.equal(diff.visualMap.nodes["node-2"].badgeLabel, "− REMOVED");
    assert.match(diff.visualMap.nodes["node-2"].styleClass, /ring-rose-500/);

    assert.ok(diff.visualMap.nodes["node-1"]);
    assert.equal(diff.visualMap.nodes["node-1"].status, "modified");
    assert.equal(diff.visualMap.nodes["node-1"].badgeLabel, "~ MODIFIED");
    assert.deepEqual(diff.visualMap.nodes["node-1"].changedFields, ["label"]);
    assert.match(diff.visualMap.nodes["node-1"].styleClass, /ring-amber-500/);

    // Verify edge visual markers
    assert.ok(diff.visualMap.edges["e-1-3"]);
    assert.equal(diff.visualMap.edges["e-1-3"].status, "added");
    assert.equal(diff.visualMap.edges["e-1-3"].strokeColor, "#10b981");

    assert.ok(diff.visualMap.edges["e-1-2"]);
    assert.equal(diff.visualMap.edges["e-1-2"].status, "removed");
    assert.equal(diff.visualMap.edges["e-1-2"].strokeColor, "#f43f5e");
  });

  it("integrates diffMarker into WorkflowNodeData correctly", () => {
    const nodeData: WorkflowNodeData = {
      ...createNodeData("webhook", "Webhook Endpoint"),
      diffMarker: {
        nodeId: "test-node",
        status: "added",
        styleClass: "ring-2 ring-emerald-500",
        badgeLabel: "+ ADDED",
        changedFields: ["all"],
      },
    };

    assert.equal(nodeData.type, "webhook");
    assert.equal(nodeData.label, "Webhook Endpoint");
    assert.ok(nodeData.diffMarker);
    assert.equal(nodeData.diffMarker.status, "added");
    assert.equal(nodeData.diffMarker.badgeLabel, "+ ADDED");
  });

  it("handles canvas node factory creation with consistent kinds", () => {
    const canvasNode = createCanvasNode("condition", { x: 150, y: 300 }, "cond-1");
    assert.equal(canvasNode.id, "cond-1");
    assert.equal(canvasNode.type, "logic");
    assert.equal(canvasNode.data.type, "condition");
    assert.equal(canvasNode.position.x, 150);
    assert.equal(canvasNode.position.y, 300);
  });
});
